name: test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install tools for act image (optional)
        run: (apt update && apt install -y sudo make curl wget gcc) || exit 0

      - name: Uninstall current version of Go
        run: make uninstall-go

      - name: Install Go
        run: make install-go

      - name: Install tools
        run: make setup-ci-env

      - name: Check code format with linter
        run: make lint

      - name: Testing
        run: make test
